name: Build with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build with JDK ${{ matrix.jdk }} on ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-18.04, windows-latest]
        jdk: ['1.11', '1.16']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3.0.0
      with:
        java-version: ${{ matrix.jdk }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
